enableLogging: true
showPopupsForShields: true
hoverDisplayElements: TargetPopup, EquipmentInfoPopup, Range
dragDisplayElements: TargetPopup, EquipmentInfoPopup, Range
enableTargetPopupInSimulation: true
